language: node_js
dist: jammy
before_script:
  - npm install -g gatsby-cli
node_js:
  - "20"
deploy:
  provider: script
  # Note: change "docs" to the directory where your gatsby-site lives, if necessary
  script: npm i --quiet && npm run travis-deploy
  skip_cleanup: true
  on:
    branch: v2